### ISSUE TITLE
Update to Angular 10

### ISSUE THREAD

**Issue by coryrylan** [coryrylan/ngx-lite#28]
Work in progress branch https://github.com/coryrylan/ngx-lite/tree/topic/angular-9

**Comment by david4096** [comment]
Any updates on a release? We're evaluating upgrading on https://github.com/dockstore/dockstore-ui2

Thanks for your great work!

**Comment by coryrylan** [comment]
Thanks! I am going to be blocking out some time over the next week to upgrade all packages to the latest Angular

**Comment by muellerelias** [comment]
Hi, what is the status? Can I update to Angular 10? Yesterday I received the following error "incompatible core dependency".

**Comment by coryrylan** [comment]
Updated to angular 11. Going through additional testing with follow up PR.
