### ISSUE TITLE
refactor util lib code

### ISSUE THREAD

**Issue by coryrylan** [coryrylan/ngx-lite#4]
Currently it is not easy to share util shared code between libraries. Currently the project has duplicated code across libs.

Possible but not great solutions
- symlink a util lib
- publish a util lib
- combine all libs into a core instead of stand alone packages (last resort, not ideal)

https://github.com/dherges/ng-packagr/issues/358

**Comment by jaypal412** [comment]
Hi coryrylan,
Nice plugin, I like this one but I need one help like how we can change the step to 1.5 or .5
