### ISSUE TITLE
Require Minimum/Maximum Character Limit for ngx-input-tag ?

### ISSUE THREAD

**Issue by JordanProtin** [coryrylan/ngx-lite#7]
Hi,

I use your tag input component in my Angular project for my forms.
Great job ! :+1: 

However, I can't fill a tag of more than 25 characters (spaces included).
Ex : 
- journée-du-patrimoine-fra (works well)
- journée-du-patrimoine-fran (doesn't work)
      
Is this normal ? Otherwise, how to get no restriction about the maximum number of characters ?

Thk's !

**Comment by coryrylan** [comment]
Hmmm there shouldn't be a restriction. Sounds like a bug to me. I'll see if I can take a look over the next week.
